variables:
  SCORZ_TAG: elevok-scorz-1.0

##########################################
## STAGE: CONTAINERIZE                  ##
##########################################

containerize:scorz:
  stage: containerize
  image: docker:23.0.5
  services:
    - docker:23.0.5-dind
  script:
    - docker system prune -a -f
    - docker build -t $IMAGE_NAME:$SCORZ_TAG --build-arg CI_SERVER_HOST=$CI_SERVER_HOST --build-arg CI_PROJECT_ID=$CI_PROJECT_ID --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN -f apps/scorz/web/Dockerfile.ssr .
    - docker tag $IMAGE_NAME:$SCORZ_TAG $CI_REGISTRY_IMAGE:$SCORZ_TAG
    - docker push $CI_REGISTRY_IMAGE:$SCORZ_TAG
  when: manual

##########################################
## STAGE: DEPLOY                        ##
##########################################

deploy:scorz:
  stage: deploy
  dependencies:
    - containerize:scorz
  variables:
    CONTAINER_NAME: elevok-scorz
  script:
    - ssh -o StrictHostKeyChecking=no -i $CLIENTS_KEY ubuntu@"$CLIENTS_SERVER" "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker pull $CI_REGISTRY_IMAGE:$SCORZ_TAG &&
        RUNNING_CONTAINER=\$(docker ps -aqf "name=$CONTAINER_NAME") &&
        if [ -n \"\$RUNNING_CONTAINER\" ]; then
            echo stopping and removing container $RUNNING_CONTAINER &&
            docker stop \$RUNNING_CONTAINER &&
            docker rm \$RUNNING_CONTAINER;
        fi &&
        docker system prune -a -f &&
        docker run -d -p 810:4000 -e API_SERVER=scorz.com -e BACKEND_SERVER=sfca-sbx-bck.diktup.cloud --name $CONTAINER_NAME $CI_REGISTRY_IMAGE:$SCORZ_TAG"
  when: manual