const pricingPlan = [
  {
    id: 1,
    type: 'Basic Plan',
    purpose: 'For Startup',
    planIcon: 'ri-book-mark-line',
    rate: 59,
    projects: 3,
    Customers: 299,
    FTP: 5,
    pmClass: 'danger',
    pmClassSymbol: 'close',
    hrClass: 'danger',
    hrClassSymbol: 'close',
    mobileClass: 'danger',
    mobileClassSymbol: 'close',
    ribbon: false,
    planButtonClassname: 'soft-success',
  },
  {
    id: 2,
    type: 'Pro Business',
    purpose: 'Professional plans',
    planIcon: 'ri-medal-line',
    rate: 180,
    projects: 15,
    Customers: 'unlimited',
    FTP: 12,
    pmClass: 'success',
    pmClassSymbol: 'checkbox',
    hrClass: 'danger',
    hrClassSymbol: 'close',
    mobileClass: 'danger',
    mobileClassSymbol: 'close',
    ribbon: true,
    planButtonClassname: 'success',
  },
  {
    id: 3,
    type: 'Platinum Plan',
    purpose: 'Enterprise Businesses',
    planIcon: 'ri-stack-line',
    rate: 290,
    projects: 'unlimited',
    Customers: 'unlimited',
    FTP: 'unlimited',
    pmClass: 'success',
    pmClassSymbol: 'checkbox',
    hrClass: 'success',
    hrClassSymbol: 'checkbox',
    mobileClass: 'success',
    mobileClassSymbol: 'checkbox',
    ribbon: false,
    planButtonClassname: 'soft-success',
  },
];

export { pricingPlan };
