export const feather = [
  'activity',
  'airplay',
  'alert-circle',
  'alert-octagon',
  'alert-triangle',
  'align-center',
  'align-justify',
  'align-left',
  'align-right',
  'anchor',
  'aperture',
  'archive',
  'arrow-down-circle',
  'arrow-down-left',
  'arrow-down-right',
  'arrow-down',
  'arrow-left-circle',
  'arrow-left',
  'arrow-right-circle',
  'arrow-right',
  'arrow-up-circle',
  'arrow-up-left',
  'arrow-up-right',
  'arrow-up',
  'at-sign',
  'award',
  'bar-chart-2',
  'bar-chart',
  'battery-charging',
  'battery',
  'bell-off',
  'bell',
  'bluetooth',
  'bold',
  'book-open',
  'book',
  'bookmark',
  'box',
  'briefcase',
  'calendar',
  'camera-off',
  'camera',
  'cast',
  'check-circle',
  'check-square',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevrons-down',
  'chevrons-left',
  'chevrons-right',
  'chevrons-up',
  'chrome',
  'circle',
  'clipboard',
  'clock',
  'cloud-drizzle',
  'cloud-lightning',
  'cloud-off',
  'cloud-rain',
  'cloud-snow',
  'cloud',
  'code',
  'codepen',
  'codesandbox',
  'coffee',
  'columns',
  'command',
  'compass',
  'copy',
  'corner-down-left',
  'corner-down-right',
  'corner-left-down',
  'corner-left-up',
  'corner-right-down',
  'corner-right-up',
  'corner-up-left',
  'corner-up-right',
  'cpu',
  'credit-card',
  'crop',
  'crosshair',
  'database',
  'delete',
  'disc',
  'dollar-sign',
  'download-cloud',
  'download',
  'droplet',
  'edit-2',
  'edit-3',
  'edit',
  'external-link',
  'eye-off',
  'eye',
  'facebook',
  'fast-forward',
  'feather',
  'figma',
  'file-minus',
  'file-plus',
  'file-text',
  'file',
  'film',
  'filter',
  'flag',
  'folder-minus',
  'folder-plus',
  'folder',
  'framer',
  'frown',
  'gift',
  'git-branch',
  'git-commit',
  'git-merge',
  'git-pull-request',
  'github',
  'gitlab',
  'globe',
  'grid',
  'hard-drive',
  'hash',
  'headphones',
  'heart',
  'help-circle',
  'hexagon',
  'home',
  'image',
  'inbox',
  'info',
  'instagram',
  'italic',
  'key',
  'layers',
  'layout',
  'life-buoy',
  'link-2',
  'link',
  'linkedin',
  'list',
  'loader',
  'lock',
  'log-in',
  'log-out',
  'mail',
  'map-pin',
  'map',
  'maximize-2',
  'maximize',
  'meh',
  'menu',
  'message-circle',
  'message-square',
  'mic-off',
  'mic',
  'minimize-2',
  'minimize',
  'minus-circle',
  'minus-square',
  'minus',
  'monitor',
  'moon',
  'more-horizontal',
  'more-vertical',
  'mouse-pointer',
  'move',
  'music',
  'navigation-2',
  'navigation',
  'octagon',
  'package',
  'paperclip',
  'pause-circle',
  'pause',
  'pen-tool',
  'percent',
  'phone-call',
  'phone-forwarded',
  'phone-incoming',
  'phone-missed',
  'phone-off',
  'phone-outgoing',
  'phone',
  'pie-chart',
  'play-circle',
  'play',
  'plus-circle',
  'plus-square',
  'plus',
  'pocket',
  'power',
  'printer',
  'radio',
  'refresh-ccw',
  'refresh-cw',
  'repeat',
  'rewind',
  'rotate-ccw',
  'rotate-cw',
  'rss',
  'save',
  'scissors',
  'search',
  'send',
  'server',
  'settings',
  'share-2',
  'share',
  'shield-off',
  'shield',
  'shopping-bag',
  'shopping-cart',
  'shuffle',
  'sidebar',
  'skip-back',
  'skip-forward',
  'slack',
  'slash',
  'sliders',
  'smartphone',
  'smile',
  'speaker',
  'square',
  'star',
  'stop-circle',
  'sun',
  'sunrise',
  'sunset',
  'tablet',
  'tag',
  'target',
  'terminal',
  'thermometer',
  'thumbs-down',
  'thumbs-up',
  'toggle-left',
  'toggle-right',
  'tool',
  'trash-2',
  'trash',
  'trello',
  'trending-down',
  'trending-up',
  'triangle',
  'truck',
  'tv',
  'twitch',
  'twitter',
  'type',
  'umbrella',
  'underline',
  'unlock',
  'upload-cloud',
  'upload',
  'user-check',
  'user-minus',
  'user-plus',
  'user-x',
  'user',
  'users',
  'video-off',
  'video',
  'voicemail',
  'volume-1',
  'volume-2',
  'volume-x',
  'volume',
  'watch',
  'wifi-off',
  'wifi',
  'wind',
  'x-circle',
  'x-octagon',
  'x-square',
  'x',
  'youtube',
  'zap-off',
  'zap',
  'zoom-in',
  'zoom-out',
];

/**
 * Deals Status
 */
const DealsStatus = [
  {
    name: 'Absternet LLC',
    date: 'Sep 20, 2021',
    profile: 'assets/images/users/avatar-1.jpg',
    userName: 'Donald Risher',
    status: 'Deal Won',
    value: '100.1K',
  },
  {
    name: 'Raitech Soft',
    date: 'Sep 23, 2021',
    profile: 'assets/images/users/avatar-2.jpg',
    userName: 'Sofia Cunha',
    status: 'Intro Call',
    value: '150K',
  },
  {
    name: 'William PVT',
    date: 'Sep 27, 2021',
    profile: 'assets/images/users/avatar-3.jpg',
    userName: 'Luis Rocha',
    status: 'Stuck',
    value: '78.18K',
  },
  {
    name: 'Loiusee LLP',
    date: 'Sep 30, 2021',
    profile: 'assets/images/users/avatar-4.jpg',
    userName: 'Vitoria Rodrigues',
    status: 'Deal Won',
    value: '180K',
  },
  {
    name: 'Apple Inc.',
    date: 'Sep 30, 2021',
    profile: 'assets/images/users/avatar-6.jpg',
    userName: 'Vitoria Rodrigues',
    status: 'New Lead',
    value: '78.9K',
  },
];

/**
 * Upcoming Activities
 */
const UpcomingActivities = [
  {
    date: '25',
    day: 'Tue',
    time: '12:00am - 03:30pm',
    content: 'Meeting for campaign with sales team',
    users: [
      {
        name: 'Stine Nielsen',
        profile: 'assets/images/users/avatar-1.jpg',
      },
      {
        name: 'Jansh Brown',
        profile: 'assets/images/users/avatar-2.jpg',
      },
      {
        name: 'Dan Gibson',
        profile: 'assets/images/users/avatar-3.jpg',
      },
      {
        name: '5',
        variant: 'bg-info',
      },
    ],
  },
  {
    date: '20',
    day: 'Wed',
    time: '02:00pm - 03:45pm',
    content: 'Adding a new event with attachments',
    users: [
      {
        name: 'Frida Bang',
        profile: 'assets/images/users/avatar-4.jpg',
      },
      {
        name: 'Malou Silva',
        profile: 'assets/images/users/avatar-5.jpg',
      },
      {
        name: 'Simon Schmidt',
        profile: 'assets/images/users/avatar-6.jpg',
      },
      {
        name: 'Tosh Jessen',
        profile: 'assets/images/users/avatar-7.jpg',
      },
      {
        name: '3',
        variant: 'bg-success',
      },
    ],
  },
  {
    date: '17',
    day: 'Wed',
    time: '04:30pm - 07:15pm',
    content: 'Create new project Bundling Product',
    users: [
      {
        name: 'Nina Schmidt',
        profile: 'assets/images/users/avatar-8.jpg',
      },
      {
        name: 'Stine Nielsen',
        profile: 'assets/images/users/avatar-1.jpg',
      },
      {
        name: 'Jansh Brown',
        profile: 'assets/images/users/avatar-2.jpg',
      },
      {
        name: '4',
        variant: 'bg-primary',
      },
    ],
  },
  {
    date: '12',
    day: 'Tue',
    time: '10:30am - 01:15pm',
    content: 'Weekly closed sales won checking with sales team',
    users: [
      {
        name: 'Stine Nielsen',
        profile: 'assets/images/users/avatar-1.jpg',
      },
      {
        name: 'Jansh Brown',
        profile: 'assets/images/users/avatar-5.jpg',
      },
      {
        name: 'Dan Gibson',
        profile: 'assets/images/users/avatar-2.jpg',
      },
      {
        name: '9',
        variant: 'bg-warning',
      },
    ],
  },
];

/**
 * Closing Deals
 */
const ClosingDeals = [
  {
    name: 'Acme Inc Install',
    profile: 'assets/images/users/avatar-1.jpg',
    userName: 'Donald Risher',
    amount: '96k',
    date: 'Today',
  },
  {
    name: 'Save lots Stores',
    profile: 'assets/images/users/avatar-2.jpg',
    userName: 'Jansh Brown',
    amount: '55.7k',
    date: '30 Dec 2021',
  },
  {
    name: 'William PVT',
    profile: 'assets/images/users/avatar-7.jpg',
    userName: 'Ayaan Hudda',
    amount: '102k',
    date: '25 Nov 2021',
  },
  {
    name: 'Raitech Soft',
    profile: 'assets/images/users/avatar-4.jpg',
    userName: 'Julia William',
    amount: '89.5k',
    date: '20 Sep 2021',
  },
  {
    name: 'Absternet LLC',
    profile: 'assets/images/users/avatar-4.jpg',
    userName: 'Vitoria Rodrigues',
    amount: '89.5k',
    date: '20 Sep 2021',
  },
];

export { DealsStatus, UpcomingActivities, ClosingDeals };
