const recomendedjob = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '(123) 456-7890',
    address: '123 Main St, Cityville',
    birthdate: '1990-01-15',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '(456) 789-0123',
    address: '456 Oak St, Townsville',
    birthdate: '1985-05-20',
  },
  {
    id: '3',
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    phone: '(789) 012-3456',
    address: '789 Pine St, Villageton',
    birthdate: '1978-11-10',
  },
  {
    id: '4',
    name: 'Alice Williams',
    email: 'alice.williams@example.com',
    phone: '(234) 567-8901',
    address: '234 Maple St, Hamletville',
    birthdate: '1995-03-25',
  },
  {
    id: '5',
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    phone: '(567) 890-1234',
    address: '567 Elm St, Suburbia',
    birthdate: '1980-09-12',
  },
  {
    id: '6',
    name: 'Eva Davis',
    email: 'eva.davis@example.com',
    phone: '(890) 123-4567',
    address: '890 Oak St, Countryside',
    birthdate: '1992-07-08',
  },
  {
    id: '7',
    name: 'Frank White',
    email: 'frank.white@example.com',
    phone: '(345) 678-9012',
    address: '345 Birch St, Riverside',
    birthdate: '1987-04-30',
  },
  {
    id: '8',
    name: 'Grace Miller',
    email: 'grace.miller@example.com',
    phone: '(678) 901-2345',
    address: '678 Pine St, Mountainside',
    birthdate: '1976-12-18',
  },
  {
    id: '9',
    name: 'Harry Taylor',
    email: 'harry.taylor@example.com',
    phone: '(901) 234-5678',
    address: '901 Cedar St, Lakeside',
    birthdate: '1983-06-05',
  },
  {
    id: '10',
    name: 'Ivy Martinez',
    email: 'ivy.martinez@example.com',
    phone: '(123) 456-7890',
    address: '123 Redwood St, Hilltop',
    birthdate: '1998-10-22',
  },
  {
    id: '11',
    name: 'Jack Robinson',
    email: 'jack.robinson@example.com',
    phone: '(234) 567-8901',
    address: '234 Cedar St, Seaside',
    birthdate: '1974-08-14',
  },
  {
    id: '12',
    name: 'Kelly Scott',
    email: 'kelly.scott@example.com',
    phone: '(345) 678-9012',
    address: '345 Birch St, Countryside',
    birthdate: '1993-01-28',
  },
  {
    id: '13',
    name: 'Leo Turner',
    email: 'leo.turner@example.com',
    phone: '(456) 789-0123',
    address: '456 Elm St, Riverside',
    birthdate: '1989-07-03',
  },
  {
    id: '14',
    name: 'Mia Jackson',
    email: 'mia.jackson@example.com',
    phone: '(567) 890-1234',
    address: '567 Maple St, Mountainside',
    birthdate: '1982-02-17',
  },
];

const candidate = [
  {
    id: '1',
    image: 'assets/images/users/avatar-10.jpg',
    name: 'Tonya Noble',
    insta: 'tonya',
    designation: 'Web Developer',
  },
  {
    id: '2',
    image: 'assets/images/users/avatar-1.jpg',
    name: 'Nicholas Ball',
    insta: 'nicholas',
    designation: 'Assistant / Store Keeper',
  },
  {
    id: '3',
    image: 'assets/images/users/avatar-9.jpg',
    name: 'Zynthia Marrow',
    insta: 'zynthia',
    designation: 'Full Stack Engineer',
  },
  {
    id: '4',
    image: 'assets/images/users/avatar-2.jpg',
    name: 'Cheryl Moore',
    insta: 'Cheryl',
    designation: 'Product Designer',
  },
  {
    id: '5',
    image: 'assets/images/users/avatar-5.jpg',
    name: 'Jennifer Bailey',
    insta: 'Jennifer',
    designation: 'Marketing Director',
  },
  {
    id: '6',
    image: 'assets/images/users/avatar-8.jpg',
    name: 'Hadley Leonard',
    insta: 'hadley',
    designation: 'Executive, HR Operations',
  },
];

export { recomendedjob, candidate };
