variables:
  DOCS_TAG: elevok-docs-1.0
  DOCS_PROD_TAG: elevok-docs-prod-1.0.9

##########################################
## STAGE: BUILD                         ##
##########################################

build:docs:
  stage: build
  dependencies:
    - cleanup
  script:
    - echo "Build Started ..."


##########################################
## STAGE: VERIFY                        ##
##########################################

verify:docs:
  stage: verify
  dependencies:
    - build:docs
  script:
    - echo "Verfify DOCS Started ..."

##########################################
## STAGE: CONTAINERIZE                  ##
##########################################

containerize:docs:
  stage: containerize
  image: docker:23.0.5
  services:
    - docker:23.0.5-dind
  script:
    - docker system prune -a -f
    - docker build -t $IMAGE_NAME:$DOCS_TAG --build-arg CI_SERVER_HOST=$CI_SERVER_HOST --build-arg CI_PROJECT_ID=$CI_PROJECT_ID --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN -f apps/documentation/Dockerfile .
    - docker tag $IMAGE_NAME:$DOCS_TAG $CI_REGISTRY_IMAGE:$DOCS_TAG
    - docker push $CI_REGISTRY_IMAGE:$DOCS_TAG
  when: manual

containerize:docs:prod:
  stage: containerize
  dependencies:
    - verify:docs
  image: docker:23.0.5
  services:
    - docker:23.0.5-dind
  script:
    - docker system prune -a -f
    - docker build -t $IMAGE_NAME:$DOCS_PROD_TAG --build-arg CI_SERVER_HOST=$CI_SERVER_HOST --build-arg CI_PROJECT_ID=$CI_PROJECT_ID --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN -f apps/documentation/Dockerfile .
    - docker tag $IMAGE_NAME:$DOCS_PROD_TAG $CI_REGISTRY_IMAGE:$DOCS_PROD_TAG
    - docker push $CI_REGISTRY_IMAGE:$DOCS_PROD_TAG
  when: manual

##########################################
## STAGE: DEPLOY                        ##
##########################################

deploy:docs:
  stage: deploy
  dependencies:
    - containerize:docs
  variables:
    CONTAINER_NAME: sifca-docs
  script:
    - ssh -o StrictHostKeyChecking=no -i $CLIENTS_KEY ubuntu@"$CLIENTS_SERVER" "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker pull $CI_REGISTRY_IMAGE:$DOCS_TAG &&
        RUNNING_CONTAINER=\$(docker ps -aqf "name=$CONTAINER_NAME") &&
        if [ -n \"\$RUNNING_CONTAINER\" ]; then
            echo stopping and removing container $RUNNING_CONTAINER &&
            docker stop \$RUNNING_CONTAINER &&
            docker rm \$RUNNING_CONTAINER;
        fi &&
        docker system prune -a -f &&
        docker run -d -p 802:80 -e API_SERVER=sfca-sbx-prtl.diktup.cloud -e BACKEND_SERVER=sfca-sbx-bck.diktup.cloud --name $CONTAINER_NAME $CI_REGISTRY_IMAGE:$DOCS_TAG"
  when: manual
  # rules:
  #   - if: '$CI_COMMIT_MESSAGE =~ /docs/' # trigger the build step if the commit message contains the word "docs"
  #     when: always